spring:
  application:
    name: springbackend

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/scihubdb
    username: admin
    password: passwd

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "http://localhost:9090/api/v1/login/oauth2/code/google"
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG


security:
  recovery:
    user:
      tokenExpirationTime: 900 * 2
  jwt:
    secret: "12311111111111111111111111111111111111111111111111111111111111111111145"
    tokenExpirationTime: 1000
    refreshTokenExpirationTime: 10000